### ISSUE TITLE
Don't  use  uglify-js?

### ISSUE THREAD

**Issue by duythiensl** [filerjs/filer#371]
**This is my snippet code:**
```
var fs = require('fs');
var UglifyJS = require("uglify-js");
var result = UglifyJS.minify(["app.js"]);
console.log(result.code);
fs.writeFile('public/angular/app.min.js',result.code,function(err){
    if(err){
        console.log(err);
    }else{
        console.log('Script generated and saved: loc8r.min.js');
        return result.code;
    }
});
```

but console.log(result.code); response : app.js? please help me! tks.....

**Comment by humphd** [comment]
@duythiensl are you using Filer or just the node `fs` module?  It looks like the latter, which is beyond the scope of this repo.  But please correct me if I'm wrong or misunderstood.

**Comment by duythiensl** [comment]
@humphd  But currently uglify-js has a problem?

**Comment by humphd** [comment]
@duythiensl you're doing `var fs = require('fs');`, and not actually using Filer in the snippet above, which is why I was asking, since it might make sense to file your bug/ask your question in a different repository.  This one is specifically about the code for FilerJS (a browser based implementation of the `fs` module), but not actually related to `fs` or `uglify-js`.  Again, apologies if I've misunderstood, just trying to figure out if there is something you need from us specifically.

**Comment by duythiensl** [comment]
Uhmm......my issue is 
```
var UglifyJS = require("uglify-js");
var result = UglifyJS.minify(["app.js"]);
console.log(result.code);
```
log write : app.js ? Instead of the content of the javascript file is uglify.

**Comment by humphd** [comment]
OK, so this is unrelated to our code, so I'm going to close this.  However, here is some code that should do what you want.  Good luck with what you're trying to do:

```js
var UglifyJS = require("uglify-js");
var appJSContents = fs.readFileSync("app.js", "utf8");
var appJSMinified = UglifyJS.minify(appJSContents);
console.log(result.code);
```

**Comment by duythiensl** [comment]
@humphd Thank you very much!
