### ISSUE TITLE
Error running test with CRLF linebreak-style

### ISSUE THREAD

**Issue by coreyjjames** [filerjs/filer#403]
Found an issue when running tests when the linebreak-style is CRLF. The following is the last part of the error message displayed.

I am on Windows 10 using Visual Studio Code.

```console

C:\Users\Corey\Desktop\OSD600\filer\tests\spec\trailing-slashes.spec.js
   1:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:37  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   3:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   4:61  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   5:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   6:64  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   7:32  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   8:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   9:38  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  10:45  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  11:46  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  12:61  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  13:6   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  14:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  15:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 10958 problems (10958 errors, 0 warnings)
  10958 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filer@0.0.44 lint: `eslint src tests`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the filer@0.0.44 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Corey\AppData\Roaming\npm-cache\_logs\2018-09-18T18_03_36_376Z-debug.log
npm ERR! Test failed.  See above for more details.

```

**Comment by humphd** [comment]
What's happening here is related to how `autocrlf` is set in your `git` config.  You can see it found `10958` errors where an `LF` was expected, but it saw `CRLF` instead.  We use [`eslint`](https://eslint.org/) to check that line endings are `LF` (i.e., Unix style).  Git has automatically converted them all to `CRLF` for you on Windows.

We have a few options

1) We could stop having `eslint` do this check, so that people can use whatever line endings they want locally.  Then, before we merge into `master`, on Travis, we could have it do a check for line endings just to make sure things don't get altered.

2) We could add a `.gitattributes` file with `* text=auto` to tell `git` to allow any line ending but use `LF` when committing.

3) You could [fix your line endings locally](https://help.github.com/articles/dealing-with-line-endings/#platform-windows) 

@modeswitch can you help me figure this out?  I have lots of Windows users, so this will be an issue for some.  What's the right answer here?  cc'ing @Pomax too, who might have advice.

**Comment by modeswitch** [comment]
Committed code should have Unix-style (`LF`) line endings. If your local `git` is giving you `CRLF`, you should set it up to not do that (option #3 from @humphd).

**Comment by Pomax** [comment]
If you're on Windows, run the git-scm installer again, and make sure to pick the "Check out as in, commit using Unix-style line endings" during the upgrade process, and you should be good to go.
