### ISSUE TITLE
Add test for fs.watch.spec.js

### ISSUE THREAD

**Issue by AHKol** [filerjs/filer#411]
There is no test looking for a `rename` event for fs.watch() in [fs.watch.spec.js](https://github.com/filerjs/filer/blob/master/tests/spec/fs.watch.spec.js)

A test case for this may be almost identical to [it('should get a change event when renaming a file', function(done) {](https://github.com/filerjs/filer/blob/fd3de6be2c1c19421d8c83e6791cd4b19afb84c7/tests/spec/fs.watch.spec.js#L43)

I would like to be assigned this issue.

**Comment by humphd** [comment]
Interestingly, I just took a look at the code.  We don't currently support `rename` events at all with watchers.  I can't recall why that is, whether a limitation in our implementation, or an oversight.  At any rate, you should consider whether this is a good test to work on, since it would also require some code to get added to support `rename` events.  I could guide you through the process if you want.  Let me know.

**Comment by humphd** [comment]
See also https://github.com/filerjs/filer/issues/68

**Comment by modeswitch** [comment]
@humphd Watch events are weird in Filer to begin with because the same database can be accessed from multiple tabs, which don't know anything about each other. I think currently watch events are only triggered from activity in the tab where the watcher is created.

**Comment by humphd** [comment]
Our watch events do work across windows, since we leverage cross-window (same-origin) `localStorage` events to emit them.  I've used them in the past to have Brackets sessions in different tabs get updated when files "change on disk."

The issue here is that we just never bothered with renames.  I can't remember why, and it might be that node itself sucks at this.

**Comment by modeswitch** [comment]
Oh right, I remember now.

Yeah I don't recall why we didn't implement for `rename`.
