### ISSUE TITLE
npm run test:manual fails on Windows environment

### ISSUE THREAD

**Issue by Mordax** [filerjs/filer#433]
Seems like there are a few issues popping up regarding viewing the tests in browser. Let me know if I should file separate issues for this. 

This is what happens on Firefox Quantum 61.0.2 (64-bit) when running npm run test:manual (npm run test works perfectly in the chrome headless browser):

![filerbug](https://user-images.githubusercontent.com/9853904/45896555-79c36400-bda2-11e8-8714-3b242d10f321.gif)

And this error in Chrome 69.0.3497:

![chrome](https://user-images.githubusercontent.com/9853904/45896612-b0997a00-bda2-11e8-9388-efb2669c6006.PNG)

I'm running in the dreaded Windows 10 environment.

Edit: Funnily enough, it works in Microsoft Edge.

**Comment by Mordax** [comment]
I'm gonna try to tackle the Firefox issue and see what may be causing it, if that's alright.

**Comment by Mordax** [comment]
Seems like when you choose to not remember history or do private browsing in Firefox, this Indexedb issue pops up. Firefox says that Private browsing automatically blocks IndexedDB but it doesn't say that not remembering history does the same as well. 

To recreate the Chrome issue, you have to clean out the test cache (rm -rf .cache tests/dist) and then run the manual again to get that memory leak warning. If you refresh the page, the issue is fixed.

**Comment by humphd** [comment]
If you're in a Private Browsing tab, yes, this is a known limitation for Filer.  Firefox currently doesn't allow IndexedDB storage in private browsing, since it would allow for fingerprinting of a user.  Chrome does allow it, but deletes the DB after you close the tab.  There are bugs in Firefox to fix this, but it's an ongoing issue.

If the problem here is really related to Private Browsing, we can probably close this, as it's filed elsewhere in Filer and in Firefox.
