### ISSUE TITLE
Add tests for fs.promises utimes function 

### ISSUE THREAD

**Issue by biskit1** [filerjs/filer#527]
Perform the existing tests for the utimes function but with fs.promises.utimes() to ensure that the integration of promises in filer works as expected.
In addition, check that fs.promises.utimes() returns a promise as expected. 

Can I work on this issue?

**Comment by SeanPrashad** [comment]
Hey @biskit1 - how are you doing on this?

**Comment by biskit1** [comment]
Thanks for checking in @SeanPrashad; should have this ready for review by end of day.

**Comment by biskit1** [comment]
https://github.com/filerjs/filer/blob/e3a1187ef94d5fc627768cee13457417e7ea0035/tests/spec/fs.utimes.spec.js#L86

Is it a mistake that `futimes` is called instead of `utimes` @humphd? There are no tests for `futimes` version of the function.

**Comment by modeswitch** [comment]
@biskit1 The tests for the file descriptor versions of each function (`fstat`, `futimes`, etc) live with the non-descriptor versions. That particular test is making sure that passing a bad descriptor to `futimes` has the correct behavior. The test only makes sense for `futimes` since `utimes` doesn't accept a descriptor.

**Comment by biskit1** [comment]
Thanks @modeswitch, that makes sense. Should have spent more time tracking the calls. That would also probably explain why my test is failing (https://github.com/filerjs/filer/pull/540/files#r221447167- except I still don't get why it was passing when I did not have the `return` there- if you see this and have an answer before I come up with one, please share 😏).
