### ISSUE TITLE
Export FS type to the user

### ISSUE THREAD

**Issue by cancerberoSgx** [filerjs/filer#754]
I think types like `FS` should be  exported since they are required in order to declare any layer on top of this (awesome) library and reference backends generically. Currently I had to copy& paste it . Maybe I'm missing something, but although is great the project is TypeScript, I think  it should expose more types. I'm not talking about users implementing / extending new backends, but I think just referring to types generically is not currently possible . (If I'm right), would you accept a PR with a couple of suggestions?  Thanks!

**Comment by humphd** [comment]
I don't tend to work in TypeScript, but I'm open to suggestions around how to better support it for users of the library.  Can you talk about what you're thinking?

I'm particularly interested in how to keep this maintainable, since there is some refactoring we might want to do at some point with the top-level API.  However, I think that the `fs` side of things will be pretty stable, since it mirrors node.

**Comment by humphd** [comment]
@cancerberoSgx I see you closed this.  If you change your mind, I'm happy to chat more if you decide you want to move forward on something like this.
